apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - name: sample-api
        image: myacrdev.azurecr.io/sample-api:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
{{ toYaml .Values.resources | indent 10 }}


