apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-api.fullname" . }}
  labels:
    {{- include "sample-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "sample-api.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          # httpGet for liveness/readiness probes if defined
          # livenessProbe:
          #   {{- toYaml .Values.livenessProbe | nindent 12 }}
          # readinessProbe:
          #   {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: DB_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: DB_PASSWORD # Consider using secrets for passwords
              value: {{ .Values.postgresql.password | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.database | quote }}
            {{- end }}
            # Add other environment variables from .Values.env
            {{- range $key, $value := .Values.env }}
            {{- if and (ne $key "NODE_ENV") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          # resources:
          #   {{- toYaml .Values.resources | nindent 12 }}
