name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./app  # Specify the app directory

      - name: Build the app
        run: npm run build
        working-directory: ./app  # Specify the app directory

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CRED }}  # Service principal credentials

      # Uncomment the following steps to push the image to ACR
      # - name: Build Docker image
      #   run: |
      #     docker build -t youracrname.azurecr.io/your-app-name:latest .
      #
      # - name: Log in to ACR
      #   run: |
      #     echo ${{ secrets.AZ_CRED }} | docker login youracrname.azurecr.io --username your-client-id --password-stdin
      #
      # - name: Push Docker image to ACR
      #   run: |
      #     docker push youracrname.azurecr.io/your-app-name:latest