name: Build App Container

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'app/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CRED }}  # Service principal credentials

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: false  # Set to false since we are not pushing to ACR
          tags: |
            hello-world:${{ github.sha }}  # Local tag for the built image

      # Uncomment the following steps to push the image to ACR when ready
      # - name: Push Docker Image to ACR
      #   run: |
      #     docker push youracrname.azurecr.io/hello-world:${{ github.sha }}
      #     docker push youracrname.azurecr.io/hello-world:latest