name: Build App Container

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag for the Docker image'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CRED }}  # Service principal credentials

      - name: Build and Push Docker Image to ACR
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.event.inputs.image_tag }}
            ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:latest
```
