name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Trigger only when files in terraform directory change
      - '.github/workflows/terraform-infra.yml' # Or when this workflow itself changes
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-infra:
    name: Terraform Deploy Infrastructure # Adding a more descriptive job name
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Using user's preferred secret name

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.5" # Specifying Terraform version

      - name: Terraform Init
        run: terraform init -input=false # Added -input=false

      - name: Terraform Validate # Adding validate step
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Show Plan
        if: always()
        run: terraform show -no-color tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan
```
