name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Trigger only when files in terraform directory change
      - '.github/workflows/terraform-infra.yml' # Or when this workflow itself changes
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure using service principal (needs AZURE_CREDENTIALS secret)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform Init
      - name: Terraform Init
        run: |
          cd infra
          terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve tfplan
