name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Trigger only when files in terraform directory change
      - '.github/workflows/terraform-infra.yml' # Or when this workflow itself changes
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

working-directory: terraform
      # Login to Azure using service principal (needs AZURE_CREDENTIALS secret)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform Init
      - name: Terraform Init
        run: |
          cd infra
          terraform init

      # Terraform Plan
      - name: Terraform Plan
        id: plan # Added id for potential future use (e.g. outputting plan)
        run: terraform plan -input=false -no-color -out=tfplan
        working-directory: terraform

      # Optional: Add a step to output the plan, e.g., for pull request comments
      # - name: Show Plan
      #   run: terraform show -no-color tfplan
      #   working-directory: terraform


      # Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only apply on direct push to main
        run: terraform apply -auto-approve -input=false tfplan
        working-directory: terraform
