name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Trigger only when files in terraform directory change
      - '.github/workflows/terraform-infra.yml' # Or when this workflow itself changes
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-infra: # Renamed from apply_infrastructure for consistency with user's version
    name: Terraform Deploy Infrastructure # More descriptive job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CRED }} # Standardized to AZ_CRED; user should ensure this secret exists

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.5" # Specify Terraform version

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        id: plan # Added id for potential future use (e.g. outputting plan)
        run: terraform plan -input=false -no-color -out=tfplan
        working-directory: terraform

      # Optional: Add a step to output the plan, e.g., for pull request comments
      # - name: Show Plan
      #   run: terraform show -no-color tfplan
      #   working-directory: terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only apply on direct push to main
        run: terraform apply -auto-approve -input=false tfplan
        working-directory: terraform
```
