name: Terraform Infrastructure CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'The Terraform action to perform: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Show Plan
        if: always()
        run: terraform show -no-color tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy' && github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false tfplan
